name: spvd
channels:
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch=2.0.0
  - pytorch-cluster=1.6.3
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - pytorch-scatter=2.1.2
  - pytorch-sparse=0.6.18
  - pytorch-spline-conv=1.2.2
  - lightning=2.3.3
  - lightning-utilities=0.11.7
  - pytorch-lightning=2.3.3
  - pyg=2.5.2
  - jupyterlab
  - fastcore=1.5.43
  - timm=1.0.3
  - open3d=0.18.0
  - pip
  - pip:
      - torch-geometric
      - torch-scatter